version: "3.3"
services:
  service1:
    image: service1
    build: ./Service1
    environment:
      STORYDBURI: ${STORYDBURI}
      SECRETKEY: ${SECRETKEY}
#    deploy:
#      replicas: 3
  service2:
    image: service2
    build: ./Service2
  service3:
    image: service3
    build: ./Service3
  service4:
    image: service4
    build: ./Service4

  service_nginx:
    image: service_nginx
    build: ./Nginx
    ports:
        - "80:80"
#    networks:
#        - ingress
    depends_on:
        - service1
        - service2
        - service3
        - service4