version: "3.3"
services:
  service1:
    image: tpetty98/service1
    environment:
      STORYDBURI: ${STORYDBURI}
      SECRETKEY: ${SECRETKEY}
    deploy:
      replicas: 3
  service2:
    image: tpetty98/service2
  service3:
    image: tpetty98/service3
  service4:
    image: tpetty98/service4
    deploy:
      replicas: 2
  service_nginx:
    image: tpetty98/service_nginx
    build: ./Nginx
    ports:
        - "80:80"
#    networks:
#        - ingress
    depends_on:
        - service1
        - service2
        - service3
        - service4
    deploy:
      replicas: 2