- name: install docker
  hosts: all
  become: true
  roles:
    - docker-installation

- name: initialise docker swarm
  hosts: swarm-manager
  become: true
  roles:
    - docker-swarm-init

- name: add workers to the swarm
  hosts: swarm-workers
  become: true
  roles:
    - docker-swarm-add-workers